### ISSUE TITLE
ES modules error

### ISSUE THREAD

**Issue by kakoni** [jieter/orc-data#19]
Hi. With recent commit (https://github.com/jieter/orc-data/commit/3296f7cb7da832201ace5a7ecc035a15a8942932) I started seeing 
```Uncaught Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: 1943```
error in the console logs 

I believe this can be fixed by introducing `babel.config.json` file with content
```json
{
   "sourceType": "unambiguous"
}
```
(see https://github.com/babel/babel/issues/12731)

**Comment by jieter** [comment]
Yes thanks!

I believe I added it, but I suspect I failed to push that commit before merging. Fixed in 644328d

**Comment by jieter** [comment]
Seems to work correctly again: https://jieter.github.io/orc-data/site/index.html#BRA/BRA2567
