### ISSUE TITLE
Search field or drop down menu not displaying boat type

### ISSUE THREAD

**Issue by Seabreeze1** [jieter/orc-data#24]
Searching with boat type seems to me more difficult with the current version than before. For example, seaching with "bavaria" returns a long list in the drop down menu but the menu does not display boat types, so it is quite difficult or time consuming going through all of the matches to find the right one. Could the drop down menu be a bit wider and also display boat type directly? 

P.S. Many thanks for this very useful service to the sailing community! 👍

**Comment by jieter** [comment]
Yes, the label should reflect what is searched for, I'll add a fix.

Thanks for the report and the thumbs up
