### ISSUE TITLE
Adding data

### ISSUE THREAD

**Issue by karstenmueller** [jieter/orc-data#3]
Hi Jan Pieter,

great to see your polar data visualization. Thanks a lot!

I am trying to add some polar data. I added "GBR" to Makefile and __init__.py and tried "make rms; make site". With the latter I got unicode errors. I tried to fix them but had no luck. See [err.txt](https://github.com/jieter/orc-data/files/1114455/err.txt)

What I really try to do is to add some polar data of a Contessa 32. How can this be achieved? I guess I have to fake an ORC data file based on the polar data? See 
[contessa32_polardata.txt](https://github.com/jieter/orc-data/files/1114476/contessa32_polardata.txt) for the data.

I pushed my changes to https://github.com/karstenmueller/orc-data

Regards,
Karsten

**Comment by jieter** [comment]
You know you can use http://jieter.github.io/orc-data/site/csvplot.html to plot your .txt file right?

The whole workflow needs some tidying up #2 would improve things already. 

If you mean you would want to *add* data to the dataset shown here, I think that doesn't fit in the current workflow at all. We would need to have some set of 'extra' boats mixed in with the data from orc.org. Would be nice to have though!

I don't think I'll have much time to work on this soon, so if you like, feel free to open a PR cleaning up the workflow and allowing a second stream of data.
