### ISSUE TITLE
Question: why does the wind angle chart start at 52 degrees?

### ISSUE THREAD

**Issue by mmocny** [jieter/orc-data#41]
It seems to me that most performance boats have an optimal upwind VMG around 35-40degress.  My manufacturer provided a polar chart starting at around 30 degrees TWA or so.  52deg seems unreasonably large to start a polar diagram.

I know most boats include data about optimum beat angle for VMG, but there is typically a large gap to 52 degrees.

Besides just missing useful data points, I think this choice makes the shape of the wind plots look atypical. They all look as if the slope of VMG would "keep going up" when sailing even tighter to the wind, rather than looking like the maximum.

For example, here is the example chart for the ITA14800:

![Screenshot 2024-07-22 at 10 03 02](https://github.com/user-attachments/assets/75c7b583-8e2e-4867-aa80-70da6a49a74b)

And here is what happens when I just add an extra line for 30 degrees:

![Screenshot 2024-07-22 at 10 10 12](https://github.com/user-attachments/assets/e4556f94-419c-48b3-bc9d-557b01f9e15c)

Suddenly it looks a lot more like a traditional polar diagram to me.

---

The same issue exists for run angles, but isn't quite as bad as it's more common for run VMG to be <150deg

---

I admit that the current choice makes it easy to spot the VMG angles (i.e. typically the end points of the line) but that data is more easily just found in the table, anyway.

**Comment by jieter** [comment]
@mmocny to show VMG angles we can add something similar to the run angles. But does the data from ORC contain a speed @30 deg TWA?

**Comment by mmocny** [comment]
After filing this question I realized that indeed you are just visualizing data that comes from that source.

Therefore my question is better placed with ORC: why start the polar data there, when most of the VMG beat angles are obviously less than that?

But it seems unlikely to get changes.  Given that you interface naturally adapts to adding these data points manually, I will close this issue.  Cheers.

**Comment by jieter** [comment]
Thanks!
