### ISSUE TITLE
Generate extended CSV throws error and stops updates

### ISSUE THREAD

**Issue by tkurki** [jieter/orc-data#7]
_Generate extended CSV_ throws error in console

![image](https://user-images.githubusercontent.com/1049678/38213743-0b3971ea-36cb-11e8-8b65-62fd2c70bc06.png)

and stop selection from the list updating the detail pane.

Really nice polar presentation! I bumped into it when in the middle of researching polars for inclusion in http://signalk.org/.

**Comment by jieter** [comment]
Thanks for reporting, fixed with f4a2fa778c86491699d9f0a79949fbb266a91abb.
